//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaMotores.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Categoria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Categoria()
        {
            this.Categoria1 = new HashSet<Categoria>();
            this.Producto = new HashSet<Producto>();
        }
    
        public int id_categoria { get; set; }
        [Display(Name = "Nombre de categoria")]
        [Required(ErrorMessage = "Campo obligatorio")]
        public string nombre_categoria { get; set; }
        [Display(Name = "Descripcion")]
        [Required(ErrorMessage = "Campo obligatorio")]
        public string descripcion { get; set; }
        [Display(Name = "Categoria superior")]
        [Required(ErrorMessage = "Campo obligatorio")]
        public int id_categoria_superior { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Categoria> Categoria1 { get; set; }
        public virtual Categoria Categoria2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Producto> Producto { get; set; }
    }
}
