//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaMotores.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.Compra = new HashSet<Compra>();
        }
    
        public int id_cliente { get; set; }
        [Display(Name = "Nombre del cliente")]
        [Required(ErrorMessage = "Campo obligatorio")]
        public string nombre_cliente { get; set; }
        [Display(Name = "Apellido paterno")]
        [Required(ErrorMessage = "Campo obligatorio")]
        public string apellido_p { get; set; }
        [Display(Name = "Apellido materno")]
        [Required(ErrorMessage = "Campo obligatorio")]
        public string apellido_m { get; set; }
        [Display(Name = "Direccion")]
        [Required(ErrorMessage = "Campo obligatorio")]
        public int id_direccion { get; set; }
        [Display(Name = "Telfono")]
        [Required(ErrorMessage = "Campo obligatorio")]
        public string telefono { get; set; }
        [Display(Name = "Email")]
        [Required(ErrorMessage = "Campo obligatorio")]
        public string email { get; set; }
        [Display(Name = "Numero de la tarjeta")]
        [Required(ErrorMessage = "Campo obligatorio")]
        public Nullable<int> id_tarjeta { get; set; }
        [Display(Name = "Nombre de usuario")]
        [Required(ErrorMessage = "Campo obligatorio")]
        public string nombre_usuario { get; set; }
        [Display(Name = "Contraseña")]
        [Required(ErrorMessage = "Campo obligatorio")]
        public string contrasenia { get; set; }
        [Display(Name = "Fecha de nacimiento")]
        [Required(ErrorMessage = "Campo obligatorio")]
        public System.DateTime fecha_nacimiento { get; set; }
    
        public virtual Direccion Direccion { get; set; }
        public virtual Tarjeta Tarjeta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Compra> Compra { get; set; }
    }
}
