//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaMotores.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Detalle_compra
    {
        public int Id_compra { get; set; }
        [Display(Name = "Producto")]
        [Required(ErrorMessage = "Campo obligatorio")]
        public int id_producto { get; set; }
        [Display(Name = "Cantidad")]
        [Required(ErrorMessage = "Campo obligatorio")]
        public int cantidad { get; set; }
        [Display(Name = "Subtotal")]
        [Required(ErrorMessage = "Campo obligatorio")]
        public decimal subtotal { get; set; }
    
        public virtual Compra Compra { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
