//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaMotores.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Inventario
    {
        [Display(Name = "Nombre del producto")]
        [Required(ErrorMessage = "Campo obligatorio")]
        public int Id_producto { get; set; }
        [Display(Name = "Cantidad en exitencia")]
        [Required(ErrorMessage = "Campo obligatorio")]
        public int cantidad_inventario { get; set; }
        [Display(Name = "Estatus")]
        [Required(ErrorMessage = "Campo obligatorio")]
        public string estatus { get; set; }
        public int id_inventario { get; set; }
    
        public virtual Producto Producto { get; set; }
    }
}
