//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaMotores.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ContextoTienda : DbContext
    {
        public ContextoTienda()
            : base("name=ContextoTienda")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categoria> Categoria { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Compra> Compra { get; set; }
        public virtual DbSet<Departamento> Departamento { get; set; }
        public virtual DbSet<Detalle_compra> Detalle_compra { get; set; }
        public virtual DbSet<Direccion> Direccion { get; set; }
        public virtual DbSet<Empleado> Empleado { get; set; }
        public virtual DbSet<Galeria> Galeria { get; set; }
        public virtual DbSet<Inventario> Inventario { get; set; }
        public virtual DbSet<marca> marca { get; set; }
        public virtual DbSet<Oden_cliente> Oden_cliente { get; set; }
        public virtual DbSet<Paqueteria> Paqueteria { get; set; }
        public virtual DbSet<Producto> Producto { get; set; }
        public virtual DbSet<ProductoTienda> ProductoTienda { get; set; }
        public virtual DbSet<Puesto> Puesto { get; set; }
        public virtual DbSet<Tarjeta> Tarjeta { get; set; }
    }
}
