//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaMotores.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.Detalle_compra = new HashSet<Detalle_compra>();
            this.Inventario = new HashSet<Inventario>();
            this.Producto1 = new HashSet<Producto>();
            this.ProductoTienda = new HashSet<ProductoTienda>();
        }
    
        public int Id_producto { get; set; }
        [Display(Name = "Nombre del producto")]
        public string nombre_producto { get; set; }
        [Display(Name = "Descripción del producto")]
        public string descripcion_producto { get; set; }
        [Display(Name = "Precio al público")]
        public decimal precio { get; set; }
        [Display(Name = "Coste")]
        public decimal coste { get; set; }
        [Display(Name = "Imagen del producto")]
        public string imagen_producto { get; set; }
        [Display(Name = "Categoria")]
        public int id_categoria { get; set; }
        [Display(Name = "Ultima actualización")]
        public Nullable<System.DateTime> ultima_actualizacion { get; set; }
        [Display(Name = "Marca")]
        public int id_marca { get; set; }
        [Display(Name = "Producto relacionado")]
        public Nullable<int> id_producto_relacionado { get; set; }
        [Display(Name = "Clave única")]
        public int clave_unica { get; set; }
        [Display(Name = "Galeria")]
        public Nullable<int> id_galeria { get; set; }
        [Display(Name = "Usuario")]
        public string email_usuario { get; set; }
        [Display(Name = "Potencia(HP)")]
        public string potencia { get; set; }
        [Display(Name = "Tipo de motor")]
        public string Tipo { get; set; }
        [Display(Name = "Ancho")]
        public Nullable<decimal> ancho { get; set; }
        [Display(Name = "Alto")]
        public Nullable<decimal> alto { get; set; }
        [Display(Name = "Largo")]
        public Nullable<decimal> profundidad { get; set; }
        [Display(Name = "Peso")]
        public Nullable<decimal> peso { get; set; }
        [Display(Name = "Polos")]
        public string polos { get; set; }
        [Display(Name = "RMP")]
        public string rpm { get; set; }
        [Display(Name = "Voltaje(V)")]
        public Nullable<decimal> voltaje { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_compra> Detalle_compra { get; set; }
        public virtual Galeria Galeria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventario> Inventario { get; set; }
        public virtual marca marca { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Producto> Producto1 { get; set; }
        public virtual Producto Producto2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductoTienda> ProductoTienda { get; set; }
    }
}
