//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaMotores.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class ProductoTienda
    {
        public int Id_producto { get; set; }
        [Display(Name = "Número de búsqueda")]
        public int numBusqueda { get; set; }
        [Display(Name = "Calificación")]
        public int calificacion { get; set; }
        [Display(Name = "Número de visitas")]
        public int numVisitas { get; set; }
        [Display(Name = "¿Destacado?")]
        public string destacado { get; set; }
        [Display(Name = "Productos relacionados")]
        public int Id_producto_tienda { get; set; }
    
        public virtual Producto Producto { get; set; }
    }
}
